### ISSUE TITLE
Helm project name clash on single cluster instance

### ISSUE THREAD

**Issue by alexgroom** [nebula0248/openshift-service-mesh-federation-demo#1]
In run.sh the values should be set accordingly:
MESH_1_HELM_RELEASE_NAMESPACE="peter-ossm-helm1"
MESH_2_HELM_RELEASE_NAMESPACE="peter-ossm-helm2"

That way it will work OOTB for single cluster, and I'm pretty sure it will also work for the other modes as well. But on a single cluster there is a project name clash with the current values.

Without this change the install fails with this error and fails to set up any control planes or member rolls:

Error from server (NotFound): servicemeshcontrolplanes.maistra.io "ossm1" not found
+ '[' == InstallSuccessful ']'
./run.sh: line 90: [: ==: unary operator expected

**Comment by nebula0248** [comment]
When both meshes are deployed on the same cluster, the value of MESH_1_HELM_RELEASE_NAMESPACE and MESH_2_HELM_RELEASE_NAMESPACE must be different to prevent clashes. Thanks for the comment, I will add this remark in the README file.
